name: Build Choco package
on: [workflow_dispatch]
jobs:
  # Explore-GitHub-Actions:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  #     - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
  #     - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  #     - name: Check out repository code
  #       uses: actions/checkout@v3
  #     - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
  #     - run: echo "🖥️ The workflow is now ready to test your code on the runner."
  #     - name: List files in the repository
  #       run: |
  #         ls ${{ github.workspace }}
  #     - run: echo "🍏 This job's status is ${{ job.status }}."
  PackAndPublish:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Test powershell
        shell: pwsh
        run: |
          ls '${{github.workspace}}\puTTY CAC\'
          cat '${{github.workspace}}\puTTY CAC\putty cac.nuspec'
      -
        name: Choco pack
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack "${{github.workspace}}\puTTY CAC\putty cac.nuspec"
      -
        name: Choco api key
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: apikey -k [${{secrets.CHOCOAPIKEY}}] -source https://push.chocolatey.org/
      -
        name: Choco push
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: push -v -d -s https://push.chocolatey.org/